name: gs2020-python4geochem

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.7
  - pip
  - umap-learn
  - voila
  - ipympl
  - ipyvolume
  - widgetsnbextension
  - imagemagick
  - prompt-toolkit=3.0.4 # 3.0.5 broken on conda
  - pip:
      - jupyter_contrib_nbextensions
      - -e git+git://github.com/morganjwilliams/pyrolite.git@develop#egg=pyrolite[skl]
      - -e git+git://github.com/morganjwilliams/pyrolite-meltsutil.git@develop#egg=pyrolite-meltsutil
      - -e git+git://github.com/morganjwilliams/autopew.git@develop#egg=autopew
      - -e git+git://github.com/morganjwilliams/interferences.git@develop#egg=interferences
